language: cpp
dist: bionic

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-10
    env:
    - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - wget https://github.com/Kitware/CMake/releases/download/v3.19.1/cmake-3.19.1-Linux-x86_64.tar.gz
  - tar -xf cmake-3.19.1-Linux-x86_64.tar.gz
  - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.19.1-Linux-x86_64/bin/cmake /home/travis/bin/cmake
  - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.19.1-Linux-x86_64/bin/ctest /home/travis/bin/ctest
  - make && make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -x gcov-10 -g './build/CMakeFiles/unittests.dir/*'
